server:
  port: 8082
spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://localhost:8084

#    Eureka server configuration fetched from config server now, hence commented below
#eureka:
#    client:
#        register-with-eureka: true
#        fetch-registry: true
#        service-url:
#           defaultZone: http://localhost:8761/eureka/
#    instance:
#        hostname: localhost
#        prefer-ip-address: true