server:
  port: 8083

spring:
  application:
    name: rating-service
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  config:
    import: configserver:http://localhost:8084

#    Eureka server configuration fetched from config server now, hence commented below
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true