server:
  port: 8082

spring:
  application:
    name: rating-service
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


